-- Social Ads Expert - Database Migration SQL
-- Run this in phpPgAdmin to create all tables
-- No superuser permissions required!

-- Clients Table
CREATE TABLE IF NOT EXISTS clients (
    id VARCHAR(255) PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    company_name TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    category TEXT NOT NULL DEFAULT 'normal',
    balance DECIMAL(10, 2) NOT NULL DEFAULT 0,
    portal_id VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Facebook Marketing Table
CREATE TABLE IF NOT EXISTS facebook_marketing (
    id VARCHAR(255) PRIMARY KEY,
    client_id VARCHAR(255) NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    date TIMESTAMP NOT NULL DEFAULT NOW(),
    daily_spend DECIMAL(10, 2) DEFAULT 0,
    reach INTEGER DEFAULT 0,
    sales INTEGER DEFAULT 0,
    campaign_details TEXT,
    ad_account_id TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Website Details Table
CREATE TABLE IF NOT EXISTS website_details (
    id VARCHAR(255) PRIMARY KEY,
    client_id VARCHAR(255) NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    website_name TEXT,
    website_url TEXT,
    website_password TEXT,
    wordpress_username TEXT,
    wordpress_password TEXT,
    cpanel_username TEXT,
    cpanel_password TEXT,
    name_server_1 TEXT,
    name_server_2 TEXT,
    website_package_name TEXT,
    service_note TEXT,
    whatsapp_username TEXT,
    whatsapp_password TEXT,
    other_details TEXT,
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Transactions Table
CREATE TABLE IF NOT EXISTS transactions (
    id VARCHAR(255) PRIMARY KEY,
    client_id VARCHAR(255) NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    description TEXT,
    date TIMESTAMP NOT NULL DEFAULT NOW(),
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Invoices Table
CREATE TABLE IF NOT EXISTS invoices (
    id VARCHAR(255) PRIMARY KEY,
    client_id VARCHAR(255) NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    invoice_number TEXT NOT NULL UNIQUE,
    amount DECIMAL(10, 2) NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    line_items JSONB NOT NULL,
    issue_date TIMESTAMP NOT NULL DEFAULT NOW(),
    due_date TIMESTAMP,
    company_name TEXT DEFAULT 'Social Ads Expert',
    company_email TEXT DEFAULT 'support@agentcrm.com',
    company_phone TEXT DEFAULT '+8801XXXXXXXXX',
    company_address TEXT DEFAULT 'Dhaka, Bangladesh',
    company_website TEXT,
    currency TEXT DEFAULT 'BDT',
    work_start_date TIMESTAMP,
    work_end_date TIMESTAMP,
    discount_percent DECIMAL(5, 2) DEFAULT 0,
    vat_percent DECIMAL(5, 2) DEFAULT 0,
    brand_color TEXT DEFAULT '#BFA1FE',
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Tags Table
CREATE TABLE IF NOT EXISTS tags (
    id VARCHAR(255) PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    color TEXT NOT NULL DEFAULT '#6B7280',
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Client Tags Table (Many-to-Many)
CREATE TABLE IF NOT EXISTS client_tags (
    id VARCHAR(255) PRIMARY KEY,
    client_id VARCHAR(255) NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    tag_id VARCHAR(255) NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Offers Table
CREATE TABLE IF NOT EXISTS offers (
    id VARCHAR(255) PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    valid_until TIMESTAMP,
    is_active TEXT NOT NULL DEFAULT 'true',
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Campaign Titles Table
CREATE TABLE IF NOT EXISTS campaign_titles (
    id VARCHAR(255) PRIMARY KEY,
    client_name TEXT NOT NULL,
    budget DECIMAL(10, 2) NOT NULL,
    end_date TIMESTAMP NOT NULL,
    generated_title TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Quick Messages Table
CREATE TABLE IF NOT EXISTS quick_messages (
    id VARCHAR(255) PRIMARY KEY,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    category TEXT DEFAULT 'general',
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_facebook_marketing_client ON facebook_marketing(client_id);
CREATE INDEX IF NOT EXISTS idx_website_details_client ON website_details(client_id);
CREATE INDEX IF NOT EXISTS idx_transactions_client ON transactions(client_id);
CREATE INDEX IF NOT EXISTS idx_invoices_client ON invoices(client_id);
CREATE INDEX IF NOT EXISTS idx_client_tags_client ON client_tags(client_id);
CREATE INDEX IF NOT EXISTS idx_client_tags_tag ON client_tags(tag_id);

-- Note: UUIDs will be generated by the application code
-- No PostgreSQL extensions required!
-- ✅ All tables created successfully!
